---
# tasks file for frontend

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install nodejs
  ansible.builtin.apt:
    name: nodejs
    update_cache: yes
    cache_valid_time: 3600

- name: Install npm
  ansible.builtin.apt:
    name: npm

- name: Install http-server
  shell: npm install http-server -g

- name: Create a servise-user frontservice
  ansible.builtin.user:
    name: "{{ ssf_service_user }}"
    shell: /bin/bash
    append: yes

- name: Create a directory /var/www-data for artefact
  ansible.builtin.file:
    path: "{{ art_path }}"
    state: directory
    owner: "{{ ssf_service_user }}"
    group: "{{ ssf_service_user }}"
    mode: '0755'

- name: Copy artefact from Nexus to /var/www-data
  ansible.builtin.get_url:
    url: https://nexus.k8s.praktikum-services.tech/repository/sausage-store-kharlamov-vasily-frontend-release/com/yandex/practicum/devops/sausage-store/{{ version }}/sausage-store-{{ version }}.tar.gz
    dest: "{{ art_path }}"
    username: std-017-017
    password: '{{ nexus_pass }}'
    owner: "{{ ssf_service_user }}"
    group: "{{ ssf_service_user }}"

- name: Unpack tar.gz file to the same directory
  ansible.builtin.unarchive:
    src: "{{ art_path }}/sausage-store-{{ version }}.tar.gz"
    dest: "{{ art_path }}"
    remote_src: yes

- name: Remove archive file
  ansible.builtin.file:
    path: "{{ art_path }}/sausage-store-{{ version }}.tar.gz"
    state: absent

- name: Change owner of artefact directory
  file:
    path: "{{ art_path }}"
    owner: "{{ ssf_service_user }}"
    group: "{{ ssf_service_user }}"
    state: directory
    recurse: yes

- name: Create folder for output logs
  ansible.builtin.file:
    path: /logs/front
    state: directory
    recurse: yes
    owner: "{{ ssf_service_user }}"
    group: "{{ ssf_service_user }}"
    mode: '0755'

- name: Create service-file from template
  template:
        src: sausage-store-frontend.service.j2
        dest: /etc/systemd/system/sausage-store-frontend.service
  notify: Restart sausage-store-frontend.service

- name: Add sausage-store-frontend.service to autoloading
  ansible.builtin.service:
    name: sausage-store-frontend.service
    enabled: yes