---
# tasks file for backend

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Install latest version of "openjdk-17-jdk" ignoring "install-recommends"
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: latest
    install_recommends: no

- name: Create a servise-group jarusers
  group:
    name:  "{{ ssb_service_group }}"
    system: true
    state: present

- name: Create a service-user jarservice
  ansible.builtin.user:
    name: "{{ ssb_service_user }}"
    group: "{{ ssb_service_group }}"
    shell: /bin/bash
    append: yes

- name: Create a directory /var/jarservice for artefact
  ansible.builtin.file:
    path: "{{ art_path }}"
    state: directory
    owner: "{{ ssb_service_user }}"
    group: "{{ ssb_service_group }}"
    mode: '0755'

- name: Copy artefact from Nexus to artefact directory
  ansible.builtin.get_url:
    url: https://nexus.k8s.praktikum-services.tech/repository/sausage-store-kharlamov-vasily-backend-release/com/yandex/practicum/devops/sausage-store/{{ version }}/sausage-store-{{ version }}.jar
    dest: "{{ art_path }}"
    username: std-017-017
    password: "{{ nexus_pass }}"
    owner: "{{ ssb_service_user }}"
    group: "{{ ssb_service_group }}"

- name: Create a directory for output logs
  ansible.builtin.file:
    path: "{{ log_path }}"
    state: directory
    recurse: yes
    owner: "{{ ssb_service_user }}"
    group: "{{ ssb_service_group }}"
    mode: '0755'

- name: Create service-file from template
  template:
        src: sausage-store-backend.service.j2
        dest: /etc/systemd/system/sausage-store-backend.service
  notify: Restart sausage-store-backend.service

- name: Add sausage-store-backend.service to autoloading
  ansible.builtin.service:
    name: sausage-store-backend.service
    enabled: yes
